// web/src/pages/Price.jsx
import { useEffect, useRef, useState } from 'react'
import { Table, Input, Button, Tag, Alert } from 'antd'
import { SearchOutlined, ExportOutlined } from '@ant-design/icons'
import { useSearchParams } from 'react-router-dom'
import { comparePrices, getSupportedTLDs } from '../api/price'
import { notify } from '../utils/toast'

function fmt(v, cur) {
  return `${cur === 'CNY' ? '¥' : '$'}${Number(v).toFixed(2)}`
}

export default function Price() {
  const [params] = useSearchParams()
  const [domain, setDomain] = useState('')
  const [prices, setPrices] = useState([])
  const [loading, setLoading] = useState(false)
  const [tlds, setTlds] = useState([])

  const handleCompare = async (value) => {
    const d = String(value || domain).trim()
    if (!d) {
      notify('warning', '请输入域名')
      return
    }
    setLoading(true)
    try {
      const res = await comparePrices({ domain: d })
      setPrices(res.prices || [])
      if (!res.prices || res.prices.length === 0) notify('info', '暂无该域名的比价数据')
    } catch {
      /* interceptor */
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    getSupportedTLDs().then((res) => setTlds(res.tlds || [])).catch(() => {})
  }, [])

  const comparedRef = useRef(null)
  useEffect(() => {
    const d = params.get('domain')
    if (d && comparedRef.current !== d) {
      comparedRef.current = d
      setDomain(d)
      handleCompare(d)
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [params])

  const isCheapest = (row) => {
    const same = prices.filter((p) => p.currency === row.currency)
    if (same.length <= 1) return false
    const min = Math.min(...same.map((p) => Number(p.register_price)))
    return Number(row.register_price) === min
  }

  const columns = [
    {
      title: '注册商',
      dataIndex: 'registrar',
      key: 'registrar',
      width: 200,
      render: (v, r) => (
        <span>
          <span style={{ fontWeight: 500 }}>{v}</span>
          {r.reference && <Tag style={{ marginLeft: 8, borderRadius: 4 }}>参考</Tag>}
        </span>
      ),
    },
    { title: '后缀', dataIndex: 'tld', key: 'tld', width: 90, render: (v) => <Tag style={{ borderRadius: 4 }}>.{v}</Tag> },
    { title: '注册价', dataIndex: 'register_price', key: 'register_price', align: 'right', width: 140, render: (v, r) => <span className="price-num" style={{ color: '#dc2626' }}>{fmt(v, r.currency)}</span> },
    { title: '续费价', dataIndex: 'renew_price', key: 'renew_price', align: 'right', width: 140, render: (v, r) => <span className="price-num">{fmt(v, r.currency)}</span> },
    { title: '转入价', dataIndex: 'transfer_price', key: 'transfer_price', align: 'right', width: 140, render: (v, r) => <span className="price-num">{fmt(v, r.currency)}</span> },
    {
      title: '',
      key: 'cheapest',
      width: 90,
      align: 'center',
      render: (_, r) => (isCheapest(r) ? <Tag color="success" style={{ borderRadius: 4 }}>最低价</Tag> : null),
    },
    {
      title: '',
      key: 'action',
      width: 110,
      align: 'right',
      render: (_, r) => r.url && <Button type="link" size="small" href={r.url} target="_blank" rel="noreferrer">前往购买 <ExportOutlined /></Button>,
    },
  ]

  return (
    <div className="page">
      <div className="page-head">
        <div>
          <h1 className="page-title">域名比价</h1>
          <p className="page-sub">对比各注册商的注册 / 续费 / 转入价格</p>
        </div>
      </div>

      <div className="panel mb-16">
        <div className="panel-body" style={{ display: 'flex', gap: 12 }}>
          <Input
            size="large"
            placeholder="请输入域名，如 example.com"
            value={domain}
            onChange={(e) => setDomain(e.target.value)}
            onPressEnter={() => handleCompare()}
            style={{ maxWidth: 420 }}
          />
          <Button size="large" type="primary" icon={<SearchOutlined />} loading={loading} onClick={() => handleCompare()}>
            查询比价
          </Button>
        </div>
      </div>

      {prices.length > 0 && (
        <Alert
          type="warning"
          showIcon
          closable={false}
          style={{ marginBottom: 16, border: '1px solid #fde68a', background: '#fffbeb' }}
          message="当前价格为估算参考价（非实时注册商报价），仅用于比价参考。"
        />
      )}

      <div className="panel">
        <Table rowKey={(r) => `${r.registrar}-${r.tld}`} columns={columns} dataSource={prices} loading={loading} pagination={false} size="middle" locale={{ emptyText: '请输入域名进行比价' }} />
      </div>

      <div className="panel mt-16">
        <div className="panel-head"><h3 className="panel-title">支持的域名后缀</h3></div>
        <div className="panel-body">
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8 }}>
            {tlds.map((t) => (
              <Tag
                key={t}
                style={{ borderRadius: 4, cursor: 'pointer', padding: '4px 10px' }}
                onClick={() => {
                  const head = String(domain || '').split('.')[0]
                  const next = head ? `${head}.${t}` : `.${t}`
                  setDomain(next)
                }}
              >
                .{t}
              </Tag>
            ))}
          </div>
        </div>
      </div>
    </div>
  )
}

// web/src/views/Price.vue
<template>
  <div class="price">
    <el-card>
      <template #header>
        <div class="card-header">
          <span>域名比价</span>
        </div>
      </template>

      <el-form :inline="true" @submit.prevent="handleCompare">
        <el-form-item label="域名">
          <el-input
            v-model="domain"
            placeholder="请输入域名，如 example.com"
            style="width: 360px"
            clearable
          />
        </el-form-item>
        <el-form-item>
          <el-button type="primary" :loading="loading" @click="handleCompare">
            <el-icon><Search /></el-icon>查询比价
          </el-button>
        </el-form-item>
      </el-form>

      <el-alert
        v-if="!loading && prices.length > 0"
        type="success"
        :closable="false"
        show-icon
        style="margin-bottom: 16px"
      >
        已找到 <strong>{{ prices.length }}</strong> 个注册商的报价
      </el-alert>

      <el-table :data="prices" style="width: 100%" v-loading="loading" empty-text="请输入域名进行比价">
        <el-table-column prop="registrar" label="注册商" width="160">
          <template #default="{ row }">
            <div class="registrar-cell">
              <span class="registrar-name">{{ row.registrar }}</span>
            </div>
          </template>
        </el-table-column>
        <el-table-column prop="tld" label="后缀" width="80" align="center">
          <template #default="{ row }">
            <el-tag size="small">.{{ row.tld }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column label="注册价" width="140" align="right">
          <template #default="{ row }">
            <span class="price-main">{{ row.currency === 'CNY' ? '¥' : '$' }}{{ row.register_price.toFixed(2) }}</span>
          </template>
        </el-table-column>
        <el-table-column label="续费价" width="140" align="right">
          <template #default="{ row }">
            <span class="price-sub">{{ row.currency === 'CNY' ? '¥' : '$' }}{{ row.renew_price.toFixed(2) }}</span>
          </template>
        </el-table-column>
        <el-table-column label="转入价" width="140" align="right">
          <template #default="{ row }">
            <span class="price-sub">{{ row.currency === 'CNY' ? '¥' : '$' }}{{ row.transfer_price.toFixed(2) }}</span>
          </template>
        </el-table-column>
        <el-table-column label="最低注册价" width="140" align="right">
          <template #default="{ row }">
            <el-tag v-if="isCheapest(row)" type="success" size="small">最低价</el-tag>
          </template>
        </el-table-column>
        <el-table-column label="操作" width="120" fixed="right">
          <template #default="{ row }">
            <el-button type="primary" size="small" link @click="goRegister(row.url)">
              前往购买
            </el-button>
          </template>
        </el-table-column>
      </el-table>
    </el-card>

    <el-card style="margin-top: 20px">
      <template #header>
        <span>支持的域名后缀</span>
      </template>
      <div class="tld-list">
        <el-tag
          v-for="tld in supportedTLDs"
          :key="tld"
          class="tld-tag"
          @click="fillTLD(tld)"
        >
          .{{ tld }}
        </el-tag>
      </div>
    </el-card>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useRoute } from 'vue-router'
import { ElMessage } from 'element-plus'
import { comparePrices, getSupportedTLDs } from '../api/price'

const route = useRoute()
const domain = ref('')
const prices = ref([])
const loading = ref(false)
const supportedTLDs = ref([])

function isCheapest(row) {
  if (prices.value.length <= 1) return false
  const min = Math.min(...prices.value.map((p) => p.register_price))
  return row.register_price === min
}

function fillTLD(tld) {
  domain.value = domain.value.split('.')[0] + '.' + tld
}

function goRegister(url) {
  if (url) {
    window.open(url, '_blank')
  }
}

async function handleCompare() {
  if (!domain.value.trim()) {
    ElMessage.warning('请输入域名')
    return
  }
  loading.value = true
  try {
    const res = await comparePrices({ domain: domain.value.trim() })
    prices.value = res.prices || []
    if (prices.value.length === 0) {
      ElMessage.info('暂无该域名的比价数据')
    }
  } finally {
    loading.value = false
  }
}

onMounted(async () => {
  try {
    const res = await getSupportedTLDs()
    supportedTLDs.value = res.tlds || []
  } catch {
    // handled
  }

  if (route.query.domain) {
    domain.value = route.query.domain
    handleCompare()
  }
})
</script>

<style scoped>
.card-header {
  font-weight: 600;
  font-size: 16px;
}

.registrar-cell {
  display: flex;
  align-items: center;
}

.registrar-name {
  font-weight: 500;
}

.price-main {
  font-size: 16px;
  font-weight: 700;
  color: #f56c6c;
}

.price-sub {
  font-size: 14px;
  color: #909399;
}

.tld-list {
  display: flex;
  flex-wrap: wrap;
  gap: 10px;
}

.tld-tag {
  cursor: pointer;
  transition: transform 0.2s;
}

.tld-tag:hover {
  transform: scale(1.1);
}
</style>
