// web/src/pages/Registrars.jsx
import { useEffect, useMemo, useState } from 'react'
import { Table, Button, Modal, Form, Select, Input, Switch, Tag, Upload, Popconfirm, Empty, Alert } from 'antd'
import { PlusOutlined, DownloadOutlined, UploadOutlined, ImportOutlined, DeleteOutlined, CheckOutlined, CloseOutlined } from '@ant-design/icons'
import * as api from '../api/registrar'
import { notify } from '../utils/toast'
import { fmtDateTime } from '../utils/format'

export default function Registrars() {
  const [registrars, setRegistrars] = useState([])
  const [loading, setLoading] = useState(false)
  const [dialogOpen, setDialogOpen] = useState(false)
  const [editing, setEditing] = useState(null)
  const [form] = Form.useForm()
  const [submitLoading, setSubmitLoading] = useState(false)
  const [importOpen, setImportOpen] = useState(false)
  const [importRegistrar, setImportRegistrar] = useState(null)
  const [importText, setImportText] = useState('')
  const [importLoading, setImportLoading] = useState(false)
  const [cnTypes, setCnTypes] = useState([])
  const [globalTypes, setGlobalTypes] = useState([])

  const allTypes = useMemo(() => [...cnTypes, ...globalTypes], [cnTypes, globalTypes])

  const fetchRegistrars = async () => {
    setLoading(true)
    try {
      const res = await api.getRegistrars()
      setRegistrars(res.data || [])
    } finally {
      setLoading(false)
    }
  }

  const fetchTypes = async () => {
    try {
      const res = await api.getRegistrarTypes()
      const all = res.data || []
      setCnTypes(all.filter((t) => t.region === 'cn'))
      setGlobalTypes(all.filter((t) => t.region === 'global' || t.region === 'other'))
    } catch {
      setCnTypes([{ value: 'aliyun', label: '阿里云（万网）' }, { value: 'tencent', label: '腾讯云（DNSPod）' }, { value: 'huawei', label: '华为云' }])
      setGlobalTypes([{ value: 'aliyun_intl', label: '阿里云（国际）' }, { value: 'tencent_intl', label: '腾讯云（国际）' }, { value: 'cloudflare', label: 'Cloudflare' }, { value: 'godaddy', label: 'GoDaddy' }, { value: 'namecheap', label: 'Namecheap' }, { value: 'namesilo', label: 'NameSilo' }, { value: 'dynadot', label: 'Dynadot' }, { value: 'digitalplat', label: 'DigitalPlat（免费域名）' }, { value: 'other', label: '其他（手动导入）' }])
    }
  }

  useEffect(() => {
    fetchRegistrars()
    fetchTypes()
  }, [])

  const typeLabel = (type) => allTypes.find((t) => t.value === type)?.label || type
  const isCN = (type) => cnTypes.some((t) => t.value === type)

  const openDialog = (row) => {
    setEditing(row || null)
    if (row) {
      form.setFieldsValue({
        name: row.name,
        type: row.type,
        api_endpoint: row.api_endpoint || '',
        api_key: row.api_key || '',
        api_secret: row.api_secret || '',
        api_extra: row.api_extra || '',
        enabled: row.enabled,
        sync_enabled: row.sync_enabled,
      })
    } else {
      form.resetFields()
    }
    setDialogOpen(true)
  }

  const handleSubmit = async () => {
    const values = await form.validateFields()
    setSubmitLoading(true)
    try {
      if (editing) {
        await api.updateRegistrar(editing.id, values)
        notify('success', '更新成功')
      } else {
        await api.createRegistrar(values)
        notify('success', '添加成功')
      }
      setDialogOpen(false)
      fetchRegistrars()
    } catch {
      /* interceptor */
    } finally {
      setSubmitLoading(false)
    }
  }

  const handleDelete = async (id) => {
    await api.deleteRegistrar(id)
    notify('success', '注册商已删除')
    fetchRegistrars()
  }

  const toggleField = async (row, field) => {
    const prev = row[field]
    setRegistrars((list) => list.map((x) => (x.id === row.id ? { ...x, [field]: !prev } : x)))
    try {
      await api.updateRegistrar(row.id, { [field]: !prev })
    } catch {
      setRegistrars((list) => list.map((x) => (x.id === row.id ? { ...x, [field]: prev } : x)))
    }
  }

  const openImport = (row) => {
    setImportRegistrar(row)
    setImportText('')
    setImportOpen(true)
  }

  const handleImport = async () => {
    setImportLoading(true)
    try {
      const res = await api.importDomains({ registrar_id: importRegistrar.id, domains: importText.trim() })
      if (res.error) {
        notify('error', res.error)
      } else if (res.imported === 0 && res.skipped === 0 && (res.refreshed || 0) === 0) {
        notify('warning', '未导入任何域名。支持自动导入的注册商：阿里云、腾讯云、Cloudflare、GoDaddy、Namecheap、NameSilo、Dynadot、DigitalPlat。其他类型请手动输入域名列表。')
      } else {
        notify('success', res.message || `导入完成：新增 ${res.imported}，刷新 ${res.refreshed || 0}，跳过 ${res.skipped}`)
      }
      setImportOpen(false)
    } catch {
      /* interceptor */
    } finally {
      setImportLoading(false)
    }
  }

  const handleExport = async () => {
    try {
      const blob = await api.exportRegistrars()
      const url = URL.createObjectURL(new Blob([blob], { type: 'text/csv;charset=utf-8' }))
      const a = document.createElement('a')
      a.href = url
      a.download = 'registrars_export.csv'
      a.click()
      URL.revokeObjectURL(url)
      notify('success', '导出成功')
    } catch {
      /* interceptor */
    }
  }

  const handleImportCSV = async (file) => {
    const fd = new FormData()
    fd.append('file', file)
    try {
      const res = await api.importRegistrarsCSV(fd)
      notify('success', res.message || `导入完成：新建 ${res.created}，更新 ${res.updated}，跳过 ${res.skipped}`)
      fetchRegistrars()
    } catch {
      /* interceptor */
    }
  }

  const columns = [
    { title: '名称', dataIndex: 'name', key: 'name', width: 150, render: (v) => <span style={{ fontWeight: 500 }}>{v}</span> },
    {
      title: '类型',
      dataIndex: 'type',
      key: 'type',
      width: 170,
      render: (v) => (
        <Tag color={v.startsWith('aliyun') || v.startsWith('tencent') || v.startsWith('huawei') ? 'red' : 'blue'} style={{ borderRadius: 4 }}>
          {typeLabel(v)}
        </Tag>
      ),
    },
    { title: '地区', dataIndex: 'type', key: 'region', width: 70, align: 'center', render: (v) => (isCN(v) ? <Tag style={{ borderRadius: 4 }}>国内</Tag> : <Tag style={{ borderRadius: 4 }}>国际</Tag>) },
    {
      title: 'API 配置',
      key: 'api',
      width: 110,
      render: (_, r) =>
        r.api_key ? (
          <span style={{ color: '#16a34a' }}><CheckOutlined /> 已配置</span>
        ) : (
          <span className="faint"><CloseOutlined /> 未配置</span>
        ),
    },
    { title: '自动同步', dataIndex: 'sync_enabled', key: 'sync_enabled', width: 90, align: 'center', render: (v, r) => <Switch size="small" checked={!!v} onChange={() => toggleField(r, 'sync_enabled')} /> },
    { title: '启用', dataIndex: 'enabled', key: 'enabled', width: 70, align: 'center', render: (v, r) => <Switch size="small" checked={!!v} onChange={() => toggleField(r, 'enabled')} /> },
    { title: '最后同步', dataIndex: 'last_sync_at', key: 'last_sync_at', width: 160, render: (v) => fmtDateTime(v) },
    {
      title: '操作',
      key: 'actions',
      fixed: 'right',
      width: 200,
      render: (_, r) => (
        <>
          <Button type="text" size="small" icon={<ImportOutlined />} onClick={() => openImport(r)}>导入域名</Button>
          <Button type="text" size="small" onClick={() => openDialog(r)}>编辑</Button>
          <Popconfirm title="确定删除此注册商？" onConfirm={() => handleDelete(r.id)}>
            <Button type="text" size="small" danger icon={<DeleteOutlined />}>删除</Button>
          </Popconfirm>
        </>
      ),
    },
  ]

  return (
    <div className="page">
      <div className="page-head">
        <div>
          <h1 className="page-title">注册商管理</h1>
          <p className="page-sub">维护注册商 API 凭据并从注册商批量导入域名</p>
        </div>
        <div className="page-actions">
          <Button icon={<DownloadOutlined />} onClick={handleExport}>导出</Button>
          <Upload accept=".csv" showUploadList={false} beforeUpload={(file) => { handleImportCSV(file); return false }}>
            <Button icon={<UploadOutlined />}>导入</Button>
          </Upload>
          <Button type="primary" icon={<PlusOutlined />} onClick={() => openDialog(null)}>添加注册商</Button>
        </div>
      </div>

      <div className="panel">
        <Table rowKey="id" columns={columns} dataSource={registrars} loading={loading} size="middle" scroll={{ x: 1000 }} locale={{ emptyText: <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="暂无注册商配置" /> }} />
      </div>

      <Modal title={editing ? '编辑注册商' : '添加注册商'} open={dialogOpen} onOk={handleSubmit} onCancel={() => setDialogOpen(false)} confirmLoading={submitLoading} width={580} destroyOnClose>
        <Form form={form} layout="vertical" requiredMark={false} style={{ marginTop: 16 }}>
          <Form.Item name="type" label="注册商类型" rules={[{ required: true, message: '请选择类型' }]}>
            <Select placeholder="选择注册商类型" options={[
              { label: '国内', options: cnTypes },
              { label: '国际', options: globalTypes },
            ]} />
          </Form.Item>
          <Form.Item name="name" label="名称" rules={[{ required: true, message: '请输入名称' }]}>
            <Input placeholder="自定义名称" />
          </Form.Item>
          <Form.Item name="api_endpoint" label="API 端点">
            <Input placeholder="API 地址（可选，使用默认）" />
          </Form.Item>
          {form.getFieldValue('type') === 'digitalplat' && (
            <Alert type="info" showIcon style={{ marginBottom: 16 }} message="DigitalPlat：在 https://dash.domain.digitalplat.org/dashboard/api/keys 创建 API Key 填入下方 APIKey 字段" />
          )}
          <Form.Item name="api_key" label="API Key">
            <Input placeholder="API Key / AccessKey ID" />
          </Form.Item>
          <Form.Item name="api_secret" label="API Secret">
            <Input.Password placeholder="API Secret / AccessKey Secret" />
          </Form.Item>
          <Form.Item name="api_extra" label="额外参数">
            <Input placeholder="其他参数（如 Namecheap 用户名等）" />
          </Form.Item>
          <div style={{ display: 'flex', gap: 32 }}>
            <Form.Item name="enabled" label="启用" valuePropName="checked">
              <Switch />
            </Form.Item>
            <Form.Item name="sync_enabled" label="自动同步" valuePropName="checked">
              <Switch />
            </Form.Item>
          </div>
        </Form>
      </Modal>

      <Modal title={`从「${importRegistrar?.name || ''}」导入域名`} open={importOpen} onOk={handleImport} onCancel={() => setImportOpen(false)} confirmLoading={importLoading} width={560} destroyOnClose>
        <Alert type="info" showIcon style={{ marginBottom: 16 }} message="填写域名列表或留空自动获取。" />
        <Input.TextArea
          rows={8}
          value={importText}
          onChange={(e) => setImportText(e.target.value)}
          placeholder={'每行一个域名，例如：\nexample.com\ntest.org\n\n留空则尝试从注册商 API 自动获取'}
        />
      </Modal>
    </div>
  )
}

// web/src/views/Registrars.vue
<template>
  <div class="registrar">
    <el-card>
      <template #header>
        <div class="card-header">
          <span>注册商管理</span>
          <div class="header-actions">
            <el-button size="small" @click="handleExportRegistrars">
              <el-icon><Download /></el-icon>导出
            </el-button>
            <el-upload
              ref="regUploadRef"
              :auto-upload="false"
              :show-file-list="false"
              accept=".csv"
              :on-change="handleImportRegistrarsFile"
            >
              <el-button size="small">
                <el-icon><Upload /></el-icon>导入
              </el-button>
            </el-upload>
            <el-button type="primary" @click="showDialog()">
              <el-icon><Plus /></el-icon>添加注册商
            </el-button>
          </div>
        </div>
      </template>

      <el-table :data="registrars" style="width: 100%" v-loading="loading" empty-text="暂无注册商配置">
        <el-table-column prop="name" label="名称" width="160" />
        <el-table-column label="类型" width="160">
          <template #default="{ row }">
            <el-tag :type="row.type.startsWith('aliyun') || row.type.startsWith('tencent') || row.type.startsWith('huawei') ? 'danger' : 'primary'" size="small">
              {{ typeLabel(row.type) }}
            </el-tag>
          </template>
        </el-table-column>
        <el-table-column label="地区" width="80" align="center">
          <template #default="{ row }">
            <el-tag v-if="isCN(row.type)" type="warning" size="small">国内</el-tag>
            <el-tag v-else size="small">国际</el-tag>
          </template>
        </el-table-column>
        <el-table-column label="API配置" min-width="200">
          <template #default="{ row }">
            <span v-if="row.api_key" style="color: #67C23A">
              <el-icon><Check /></el-icon> 已配置
            </span>
            <span v-else style="color: #909399">
              <el-icon><Close /></el-icon> 未配置
            </span>
          </template>
        </el-table-column>
        <el-table-column label="自动同步" width="100" align="center">
          <template #default="{ row }">
            <el-switch v-model="row.sync_enabled" size="small" @change="toggleSync(row)" />
          </template>
        </el-table-column>
        <el-table-column label="启用" width="80" align="center">
          <template #default="{ row }">
            <el-switch v-model="row.enabled" size="small" @change="toggleEnabled(row)" />
          </template>
        </el-table-column>
        <el-table-column label="最后同步" width="170">
          <template #default="{ row }">
            {{ row.last_sync_at ? new Date(row.last_sync_at).toLocaleString('zh-CN') : '从未同步' }}
          </template>
        </el-table-column>
        <el-table-column label="操作" width="180" fixed="right">
          <template #default="{ row }">
            <el-button text type="primary" size="small" @click="showImportDialog(row)">导入域名</el-button>
            <el-button text type="primary" size="small" @click="showDialog(row)">编辑</el-button>
            <el-popconfirm title="确定删除此注册商？" @confirm="handleDelete(row.id)">
              <template #reference>
                <el-button text type="danger" size="small">删除</el-button>
              </template>
            </el-popconfirm>
          </template>
        </el-table-column>
      </el-table>
    </el-card>

    <!-- Add/Edit Dialog -->
    <el-dialog
      v-model="dialogVisible"
      :title="isEdit ? '编辑注册商' : '添加注册商'"
      width="600px"
      destroy-on-close
    >
      <el-form ref="formRef" :model="form" :rules="formRules" label-width="100px">
        <el-form-item label="注册商类型" prop="type">
          <el-select v-model="form.type" placeholder="选择注册商类型" style="width: 100%" @change="onTypeChange">
            <el-option-group label="国内">
              <el-option v-for="t in cnTypes" :key="t.value" :label="t.label" :value="t.value" />
            </el-option-group>
            <el-option-group label="国际">
              <el-option v-for="t in globalTypes" :key="t.value" :label="t.label" :value="t.value" />
            </el-option-group>
          </el-select>
        </el-form-item>
        <el-form-item label="名称" prop="name">
          <el-input v-model="form.name" placeholder="自定义名称" />
        </el-form-item>
        <el-form-item label="API端点">
          <el-input v-model="form.api_endpoint" placeholder="API地址（可选，使用默认）" />
        </el-form-item>
        <el-alert
          v-if="form.type === 'digitalplat'"
          type="info"
          :closable="false"
          show-icon
          style="margin-bottom: 16px"
        >
          DigitalPlat：在 <a href="https://dash.domain.digitalplat.org/dashboard/api/keys" target="_blank" style="color:#409EFF">Dashboard → API Keys</a>
          创建 <code>dp_live_...</code> 密钥，填入下方「API Key」即可自动获取域名；WHOIS 将使用官方 RDAP 服务器 <code>rdap.digitalplat.org</code> 查询。
        </el-alert>
        <el-form-item label="API Key">
          <el-input v-model="form.api_key" placeholder="API Key / AccessKey ID / dp_live_..." show-password />
        </el-form-item>
        <el-form-item label="API Secret">
          <el-input v-model="form.api_secret" placeholder="API Secret / AccessKey Secret" show-password />
        </el-form-item>
        <el-form-item label="额外参数">
          <el-input v-model="form.api_extra" placeholder="其他参数（如用户名等）" />
        </el-form-item>
        <el-form-item label="启用">
          <el-switch v-model="form.enabled" />
        </el-form-item>
        <el-form-item label="自动同步">
          <el-switch v-model="form.sync_enabled" />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="dialogVisible = false">取消</el-button>
        <el-button type="primary" :loading="submitLoading" @click="handleSubmit">确定</el-button>
      </template>
    </el-dialog>

    <!-- Import Dialog -->
    <el-dialog
      v-model="importDialogVisible"
      title="导入域名"
      width="600px"
      destroy-on-close
    >
      <el-alert type="info" :closable="false" show-icon style="margin-bottom: 16px">
        从 <strong>{{ currentRegistrar?.name }}</strong> 导入域名到系统中。填写域名列表或留空自动获取。
      </el-alert>
      <el-form label-width="100px">
        <el-form-item label="注册商">
          <el-input :model-value="currentRegistrar?.name" disabled />
        </el-form-item>
        <el-form-item label="域名列表">
          <el-input
            v-model="importDomainsText"
            type="textarea"
            :rows="8"
            placeholder="每行一个域名，例如：&#10;example.com&#10;test.org&#10;my-site.net&#10;&#10;留空则尝试从注册商API自动获取"
          />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="importDialogVisible = false">取消</el-button>
        <el-button type="primary" :loading="importLoading" @click="handleImport">
          <el-icon><Download /></el-icon>开始导入
        </el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup>
import { ref, reactive, onMounted } from 'vue'
import { ElMessage } from 'element-plus'
import {
  getRegistrars,
  createRegistrar,
  updateRegistrar,
  deleteRegistrar,
  getRegistrarTypes,
  importDomains,
  exportRegistrars,
  importRegistrarsCSV,
} from '../api/registrar'

const registrars = ref([])
const loading = ref(false)
const dialogVisible = ref(false)
const importDialogVisible = ref(false)
const isEdit = ref(false)
const editId = ref(null)
const formRef = ref(null)
const submitLoading = ref(false)
const importLoading = ref(false)
const currentRegistrar = ref(null)
const importDomainsText = ref('')
const regUploadRef = ref(null)

const cnTypes = ref([])
const globalTypes = ref([])

const form = reactive({
  name: '',
  type: '',
  api_endpoint: '',
  api_key: '',
  api_secret: '',
  api_extra: '',
  enabled: true,
  sync_enabled: false,
})

const formRules = {
  name: [{ required: true, message: '请输入名称', trigger: 'blur' }],
  type: [{ required: true, message: '请选择类型', trigger: 'change' }],
}

function typeLabel(type) {
  const all = [...cnTypes.value, ...globalTypes.value]
  const found = all.find((t) => t.value === type)
  return found ? found.label : type
}

function isCN(type) {
  return cnTypes.value.some((t) => t.value === type)
}

function onTypeChange(val) {
  if (!form.name) {
    const all = [...cnTypes.value, ...globalTypes.value]
    const found = all.find((t) => t.value === val)
    if (found) form.name = found.label
  }
}

function showDialog(row) {
  if (row) {
    isEdit.value = true
    editId.value = row.id
    form.name = row.name
    form.type = row.type
    form.api_endpoint = row.api_endpoint || ''
    form.api_key = row.api_key || ''
    form.api_secret = row.api_secret || ''
    form.api_extra = row.api_extra || ''
    form.enabled = row.enabled
    form.sync_enabled = row.sync_enabled
  } else {
    isEdit.value = false
    editId.value = null
    form.name = ''
    form.type = ''
    form.api_endpoint = ''
    form.api_key = ''
    form.api_secret = ''
    form.api_extra = ''
    form.enabled = true
    form.sync_enabled = false
  }
  dialogVisible.value = true
}

function showImportDialog(row) {
  currentRegistrar.value = row
  importDomainsText.value = ''
  importDialogVisible.value = true
}

async function fetchRegistrars() {
  loading.value = true
  try {
    const res = await getRegistrars()
    registrars.value = res.data || []
  } finally {
    loading.value = false
  }
}

async function fetchTypes() {
  try {
    const res = await getRegistrarTypes()
    const all = res.data || []
    cnTypes.value = all.filter((t) => t.region === 'cn')
    globalTypes.value = all.filter((t) => t.region === 'global' || t.region === 'other')
  } catch {
    cnTypes.value = [
      { value: 'aliyun', label: '阿里云（万网）' },
      { value: 'tencent', label: '腾讯云（DNSPod）' },
      { value: 'huawei', label: '华为云' },
    ]
    globalTypes.value = [
      { value: 'aliyun_intl', label: '阿里云（国际）' },
      { value: 'tencent_intl', label: '腾讯云（国际）' },
      { value: 'cloudflare', label: 'Cloudflare' },
      { value: 'godaddy', label: 'GoDaddy' },
      { value: 'namecheap', label: 'Namecheap' },
      { value: 'namesilo', label: 'NameSilo' },
      { value: 'dynadot', label: 'Dynadot' },
      { value: 'digitalplat', label: 'DigitalPlat（免费域名）' },
      { value: 'porkbun', label: 'Porkbun' },
      { value: 'other', label: '其他（手动导入）' },
    ]
  }
}

async function handleSubmit() {
  await formRef.value.validate()
  submitLoading.value = true
  try {
    if (isEdit.value) {
      await updateRegistrar(editId.value, form)
      ElMessage.success('更新成功')
    } else {
      await createRegistrar(form)
      ElMessage.success('添加成功')
    }
    dialogVisible.value = false
    fetchRegistrars()
  } finally {
    submitLoading.value = false
  }
}

async function handleDelete(id) {
  await deleteRegistrar(id)
  ElMessage.success('删除成功')
  fetchRegistrars()
}

async function toggleSync(row) {
  await updateRegistrar(row.id, { sync_enabled: row.sync_enabled })
}

async function toggleEnabled(row) {
  await updateRegistrar(row.id, { enabled: row.enabled })
}

async function handleImport() {
  importLoading.value = true
  try {
    const res = await importDomains({
      registrar_id: currentRegistrar.value.id,
      domains: importDomainsText.value.trim(),
    })
    if (res.error) {
      ElMessage.error(res.error)
    } else if (res.imported === 0 && res.updated === 0 && res.skipped === 0 && (res.refreshed || 0) === 0) {
      ElMessage.warning('未导入任何域名。支持自动导入的注册商: 阿里云、腾讯云、Cloudflare、GoDaddy、Namecheap、NameSilo、Dynadot、DigitalPlat。其他类型请手动输入域名列表。')
    } else {
      ElMessage.success(
        res.message || `导入完成: 新增 ${res.imported} 个, 更新 ${res.updated} 个, 刷新 ${res.refreshed || 0} 个, 跳过 ${res.skipped} 个`
      )
    }
    importDialogVisible.value = false
    fetchRegistrars()
  } finally {
    importLoading.value = false
  }
}

// --- Export / Import ---
async function handleExportRegistrars() {
  try {
    const res = await exportRegistrars()
    const blob = new Blob([res], { type: 'text/csv;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'registrars_export.csv'
    a.click()
    URL.revokeObjectURL(url)
    ElMessage.success('导出成功')
  } catch (e) {
    ElMessage.error('导出失败: ' + (e.message || '未知错误'))
  }
}

async function handleImportRegistrarsFile(file) {
  const formData = new FormData()
  formData.append('file', file.raw)
  try {
    const res = await importRegistrarsCSV(formData)
    ElMessage.success(res.message || `导入完成: ${res.created} 个注册商`)
    fetchRegistrars()
  } catch (e) {
    ElMessage.error('导入失败: ' + (e.response?.data?.error || e.message || '未知错误'))
  }
}

onMounted(() => {
  fetchRegistrars()
  fetchTypes()
})
</script>

<style scoped>
.card-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.header-actions {
  display: flex;
  align-items: center;
  gap: 8px;
}
</style>
