// web/src/layouts/MainLayout.vue
<template>
  <el-container class="layout-container">
    <el-aside :width="isCollapse ? '64px' : '220px'" class="aside">
      <div class="logo" @click="isCollapse = !isCollapse">
        <el-icon :size="24"><Monitor /></el-icon>
        <span v-show="!isCollapse" class="logo-text">Domain Manager</span>
      </div>
      <el-menu
        :default-active="$route.path"
        :collapse="isCollapse"
        router
        background-color="#001529"
        text-color="#ffffffa6"
        active-text-color="#409EFF"
      >
        <el-menu-item index="/">
          <el-icon><DataBoard /></el-icon>
          <template #title>仪表盘</template>
        </el-menu-item>
        <el-menu-item index="/domains">
          <el-icon><Connection /></el-icon>
          <template #title>域名管理</template>
        </el-menu-item>
        <el-menu-item index="/price">
          <el-icon><Money /></el-icon>
          <template #title>域名比价</template>
        </el-menu-item>
        <el-menu-item index="/registrars">
          <el-icon><OfficeBuilding /></el-icon>
          <template #title>注册商管理</template>
        </el-menu-item>
        <el-menu-item index="/certificates">
          <el-icon><Document /></el-icon>
          <template #title>证书管理</template>
        </el-menu-item>
        <el-menu-item index="/notifications">
          <el-icon><Bell /></el-icon>
          <template #title>通知管理</template>
        </el-menu-item>
        <el-menu-item index="/profile">
          <el-icon><User /></el-icon>
          <template #title>个人设置</template>
        </el-menu-item>
      </el-menu>
    </el-aside>

    <el-container>
      <el-header class="header">
        <div class="header-left">
          <el-breadcrumb separator="/">
            <el-breadcrumb-item :to="{ path: '/' }">首页</el-breadcrumb-item>
            <el-breadcrumb-item v-if="$route.name !== 'Dashboard'">
              {{ $route.name }}
            </el-breadcrumb-item>
          </el-breadcrumb>
        </div>
        <div class="header-right">
          <el-dropdown trigger="click" @command="handleCommand">
            <span class="user-info">
              <el-avatar :size="32" icon="UserFilled" />
              <span class="username">{{ userStore.user?.username || '用户' }}</span>
              <el-icon><ArrowDown /></el-icon>
            </span>
            <template #dropdown>
              <el-dropdown-menu>
                <el-dropdown-item command="profile">个人设置</el-dropdown-item>
                <el-dropdown-item divided command="logout">退出登录</el-dropdown-item>
              </el-dropdown-menu>
            </template>
          </el-dropdown>
        </div>
      </el-header>
      <el-main class="main">
        <router-view />
      </el-main>
    </el-container>
  </el-container>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { useUserStore } from '../stores/user'

const router = useRouter()
const userStore = useUserStore()
const isCollapse = ref(false)

onMounted(() => {
  userStore.fetchProfile()
})

function handleCommand(cmd) {
  if (cmd === 'logout') {
    userStore.logout()
    router.push('/login')
  } else if (cmd === 'profile') {
    router.push('/profile')
  }
}
</script>

<style scoped>
.layout-container {
  height: 100vh;
}

.aside {
  background-color: #001529;
  transition: width 0.3s;
  overflow: hidden;
}

.logo {
  height: 60px;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 10px;
  color: #fff;
  cursor: pointer;
  border-bottom: 1px solid #ffffff1a;
}

.logo-text {
  font-size: 16px;
  font-weight: 600;
  white-space: nowrap;
}

.el-menu {
  border-right: none;
}

.header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  background: #fff;
  border-bottom: 1px solid #ebeef5;
  box-shadow: 0 1px 4px #0000000d;
  padding: 0 20px;
}

.user-info {
  display: flex;
  align-items: center;
  gap: 8px;
  cursor: pointer;
}

.username {
  font-size: 14px;
  color: #606266;
}

.main {
  background-color: #f0f2f5;
  padding: 20px;
}
</style>

// web/src/layouts/MainLayout.jsx
import { useMemo, useState } from 'react'
import { Layout, Menu, Dropdown } from 'antd'
import {
  DashboardOutlined,
  GlobalOutlined,
  DollarOutlined,
  BankOutlined,
  SafetyCertificateOutlined,
  BellOutlined,
  UserOutlined,
  LogoutOutlined,
  MenuFoldOutlined,
  MenuUnfoldOutlined,
} from '@ant-design/icons'
import { Outlet, useLocation, useNavigate } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'
import AppAvatar from '../components/AppAvatar'
import { notify } from '../utils/toast'

const { Sider, Header, Content } = Layout

const NAV = [
  { key: '/', label: '仪表盘', icon: <DashboardOutlined /> },
  { key: '/domains', label: '域名管理', icon: <GlobalOutlined /> },
  { key: '/price', label: '域名比价', icon: <DollarOutlined /> },
  { key: '/registrars', label: '注册商管理', icon: <BankOutlined /> },
  { key: '/certificates', label: '证书管理', icon: <SafetyCertificateOutlined /> },
  { key: '/notifications', label: '通知管理', icon: <BellOutlined /> },
  { key: '/profile', label: '个人设置', icon: <UserOutlined /> },
]

export default function MainLayout() {
  const [collapsed, setCollapsed] = useState(false)
  const location = useLocation()
  const navigate = useNavigate()
  const { user, logout } = useAuth()

  const selectedKey = useMemo(() => {
    const match = NAV.filter((n) => n.key !== '/' && location.pathname.startsWith(n.key)).sort(
      (a, b) => b.key.length - a.key.length
    )[0]
    return match ? match.key : '/'
  }, [location.pathname])

  const pageTitle = useMemo(() => {
    const found = NAV.find((n) => n.key === selectedKey)
    return found ? found.label : ''
  }, [selectedKey])

  const menuItems = useMemo(
    () =>
      NAV.map((n) => ({
        key: n.key,
        icon: n.icon,
        label: n.label,
      })),
    []
  )

  const userItems = [
    { key: 'profile', icon: <UserOutlined />, label: '个人设置' },
    { type: 'divider' },
    { key: 'logout', icon: <LogoutOutlined />, label: '退出登录', danger: true },
  ]

  const onUserCommand = ({ key }) => {
    if (key === 'logout') {
      logout()
      notify('success', '已退出登录')
      navigate('/login')
    } else if (key === 'profile') {
      navigate('/profile')
    }
  }

  return (
    <Layout style={{ minHeight: '100vh' }}>
      <Sider
        width={224}
        collapsedWidth={64}
        collapsible
        collapsed={collapsed}
        trigger={null}
        className="app-sider"
        theme="light"
      >
        <div className="app-logo">
          <div className="app-logo-mark">DM</div>
          {!collapsed && <div className="app-logo-text">Domain Manager</div>}
        </div>
        <Menu
          className="app-menu"
          mode="inline"
          selectedKeys={[selectedKey]}
          items={menuItems}
          onClick={({ key }) => navigate(key)}
          style={{ borderInlineEnd: 'none' }}
        />
      </Sider>
      <Layout>
        <Header className="app-header">
          <div style={{ display: 'flex', alignItems: 'center', gap: 16 }}>
            <span
              style={{ cursor: 'pointer', color: '#57534e' }}
              onClick={() => setCollapsed((c) => !c)}
            >
              {collapsed ? <MenuUnfoldOutlined /> : <MenuFoldOutlined />}
            </span>
            <span className="app-header-title">{pageTitle}</span>
          </div>
          <Dropdown menu={{ items: userItems, onClick: onUserCommand }} placement="bottomRight">
            <div className="app-user">
              <AppAvatar email={user?.email} name={user?.nickname || user?.username} size={30} />
              <span style={{ fontSize: 13, color: '#1c1917', fontWeight: 500 }}>
                {user?.nickname || user?.username || '用户'}
              </span>
              {user?.role === 'admin' && (
                <span
                  style={{
                    fontSize: 11,
                    border: '1px solid var(--border-strong)',
                    borderRadius: 4,
                    padding: '1px 6px',
                    color: '#57534e',
                  }}
                >
                  管理员
                </span>
              )}
            </div>
          </Dropdown>
        </Header>
        <Content>
          <Outlet />
        </Content>
      </Layout>
    </Layout>
  )
}
