// web/src/views/Certificates.vue
<template>
  <div class="certificates">
    <el-card>
      <template #header>
        <div class="card-header">
          <div class="header-left">
            <el-input
              v-model="keyword"
              placeholder="搜索域名或颁发者..."
              prefix-icon="Search"
              clearable
              style="width: 240px; margin-right: 12px"
              @keyup.enter="fetchCerts"
              @clear="fetchCerts"
            />
            <el-select v-model="statusFilter" placeholder="状态筛选" clearable style="width: 150px" @change="fetchCerts">
              <el-option label="正常" value="active" />
              <el-option label="已过期" value="expired" />
              <el-option label="30天内到期" value="expiring_30" />
            </el-select>
          </div>
          <div class="header-right">
            <el-button size="small" @click="showCertimateConfig = true">
              <el-icon><Setting /></el-icon>Certimate 配置
            </el-button>
            <el-button size="small" type="success" @click="handleSync" :loading="syncing">
              <el-icon><Refresh /></el-icon>同步证书
            </el-button>
            <el-button type="primary" @click="showDialog()">
              <el-icon><Plus /></el-icon>添加证书
            </el-button>
          </div>
        </div>
      </template>

      <div class="stats-row" v-if="stats">
        <el-row :gutter="16">
          <el-col :span="6">
            <el-statistic title="证书总数" :value="stats.total" />
          </el-col>
          <el-col :span="6">
            <el-statistic title="正常" :value="stats.active" />
          </el-col>
          <el-col :span="6">
            <el-statistic title="已过期" :value="stats.expired" />
          </el-col>
          <el-col :span="6">
            <el-statistic title="即将到期" :value="stats.expiring_soon" />
          </el-col>
        </el-row>
      </div>

      <el-table :data="certs" style="width: 100%" v-loading="loading" empty-text="暂无证书">
        <el-table-column prop="domain" label="域名" min-width="200" />
        <el-table-column prop="issuer" label="颁发者" width="160" />
        <el-table-column label="密钥算法" width="120">
          <template #default="{ row }">
            <el-tag size="small">{{ row.key_algorithm || '-' }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column label="生效时间" width="120">
          <template #default="{ row }">
            {{ row.not_before ? row.not_before.split('T')[0] : '-' }}
          </template>
        </el-table-column>
        <el-table-column label="到期时间" width="120">
          <template #default="{ row }">
            <span :class="getExpiryClass(row)">{{ row.not_after ? row.not_after.split('T')[0] : '-' }}</span>
          </template>
        </el-table-column>
        <el-table-column label="状态" width="100">
          <template #default="{ row }">
            <el-tag :type="row.status === 'active' ? 'success' : 'danger'" size="small">
              {{ row.status === 'active' ? '正常' : '已过期' }}
            </el-tag>
          </template>
        </el-table-column>
        <el-table-column label="来源" width="100">
          <template #default="{ row }">
            <el-tag :type="row.source === 'certimate' ? 'primary' : 'info'" size="small">
              {{ row.source === 'certimate' ? 'Certimate' : row.source || '手动' }}
            </el-tag>
          </template>
        </el-table-column>
        <el-table-column label="操作" width="180" fixed="right">
          <template #default="{ row }">
            <el-button text type="primary" size="small" @click="showDialog(row)">编辑</el-button>
            <el-button text type="info" size="small" @click="viewDetail(row)">详情</el-button>
            <el-popconfirm title="确定删除此证书？" @confirm="handleDelete(row.id)">
              <template #reference>
                <el-button text type="danger" size="small">删除</el-button>
              </template>
            </el-popconfirm>
          </template>
        </el-table-column>
      </el-table>
    </el-card>

    <!-- Add/Edit Dialog -->
    <el-dialog v-model="dialogVisible" :title="isEdit ? '编辑证书' : '添加证书'" width="650px" destroy-on-close>
      <el-form ref="formRef" :model="form" :rules="formRules" label-width="100px">
        <el-form-item label="域名" prop="domain">
          <el-input v-model="form.domain" placeholder="example.com" />
        </el-form-item>
        <el-form-item label="颁发者">
          <el-input v-model="form.issuer" placeholder="Let's Encrypt" />
        </el-form-item>
        <el-form-item label="密钥算法">
          <el-select v-model="form.key_algorithm" placeholder="选择算法" style="width: 100%">
            <el-option label="RSA 2048" value="RSA 2048" />
            <el-option label="RSA 4096" value="RSA 4096" />
            <el-option label="ECDSA P-256" value="ECDSA P-256" />
            <el-option label="ECDSA P-384" value="ECDSA P-384" />
          </el-select>
        </el-form-item>
        <el-form-item label="生效时间">
          <el-date-picker v-model="form.not_before" type="date" placeholder="选择日期" value-format="YYYY-MM-DD" style="width: 100%" />
        </el-form-item>
        <el-form-item label="到期时间">
          <el-date-picker v-model="form.not_after" type="date" placeholder="选择日期" value-format="YYYY-MM-DD" style="width: 100%" />
        </el-form-item>
        <el-form-item label="SAN 域名">
          <el-input v-model="form.subject_alt_names" placeholder="多个域名用分号分隔" />
        </el-form-item>
        <el-form-item label="来源">
          <el-select v-model="form.source" style="width: 100%">
            <el-option label="Certimate" value="certimate" />
            <el-option label="手动添加" value="manual" />
            <el-option label="Let's Encrypt" value="letsencrypt" />
          </el-select>
        </el-form-item>
        <el-form-item label="备注">
          <el-input v-model="form.note" type="textarea" :rows="2" />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="dialogVisible = false">取消</el-button>
        <el-button type="primary" @click="handleSave" :loading="saving">保存</el-button>
      </template>
    </el-dialog>

    <!-- Detail Dialog -->
    <el-dialog v-model="detailVisible" title="证书详情" width="650px">
      <el-descriptions :column="2" border v-if="detailCert">
        <el-descriptions-item label="域名" :span="2">{{ detailCert.domain }}</el-descriptions-item>
        <el-descriptions-item label="颁发者">{{ detailCert.issuer }}</el-descriptions-item>
        <el-descriptions-item label="密钥算法">{{ detailCert.key_algorithm }}</el-descriptions-item>
        <el-descriptions-item label="生效时间">{{ detailCert.not_before ? detailCert.not_before.split('T')[0] : '-' }}</el-descriptions-item>
        <el-descriptions-item label="到期时间">{{ detailCert.not_after ? detailCert.not_after.split('T')[0] : '-' }}</el-descriptions-item>
        <el-descriptions-item label="SAN 域名" :span="2">{{ detailCert.subject_alt_names || '-' }}</el-descriptions-item>
        <el-descriptions-item label="序列号" :span="2">{{ detailCert.serial_number || '-' }}</el-descriptions-item>
        <el-descriptions-item label="来源">{{ detailCert.source }}</el-descriptions-item>
        <el-descriptions-item label="状态">
          <el-tag :type="detailCert.status === 'active' ? 'success' : 'danger'" size="small">
            {{ detailCert.status === 'active' ? '正常' : '已过期' }}
          </el-tag>
        </el-descriptions-item>
        <el-descriptions-item label="备注" :span="2">{{ detailCert.note || '-' }}</el-descriptions-item>
        <el-descriptions-item label="创建时间" :span="2">{{ new Date(detailCert.created_at).toLocaleString('zh-CN') }}</el-descriptions-item>
      </el-descriptions>
    </el-dialog>

    <!-- Certimate Config Dialog -->
    <el-dialog v-model="showCertimateConfig" title="Certimate 配置" width="500px">
      <el-form :model="certimateForm" label-width="80px">
        <el-form-item label="API 地址">
          <el-input v-model="certimateForm.url" placeholder="http://127.0.0.1:8090" />
        </el-form-item>
        <el-form-item label="Token">
          <el-input v-model="certimateForm.token" type="password" show-password placeholder="PocketBase superuser token" />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="showCertimateConfig = false">取消</el-button>
        <el-button type="primary" @click="saveCertimateForm" :loading="savingConfig">保存</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { ElMessage } from 'element-plus'
import {
  getCertificates, createCertificate, updateCertificate, deleteCertificate,
  getCertificateStats, getCertimateConfig, saveCertimateConfig, syncCertimateCertificates
} from '../api/certificate'

const certs = ref([])
const stats = ref(null)
const loading = ref(false)
const keyword = ref('')
const statusFilter = ref('')
const dialogVisible = ref(false)
const detailVisible = ref(false)
const detailCert = ref(null)
const isEdit = ref(false)
const editId = ref(null)
const saving = ref(false)
const syncing = ref(false)
const showCertimateConfig = ref(false)
const savingConfig = ref(false)
const formRef = ref(null)

const certimateForm = ref({ url: '', token: '' })

const form = ref({
  domain: '', issuer: '', key_algorithm: '', not_before: '', not_after: '',
  subject_alt_names: '', source: 'certimate', note: ''
})

const formRules = {
  domain: [{ required: true, message: '请输入域名', trigger: 'blur' }]
}

onMounted(() => {
  fetchCerts()
  fetchStats()
  fetchCertimateConfig()
})

async function fetchCerts() {
  loading.value = true
  try {
    const res = await getCertificates({ keyword: keyword.value, status: statusFilter.value })
    certs.value = res.data || []
  } finally {
    loading.value = false
  }
}

async function fetchStats() {
  try {
    stats.value = await getCertificateStats()
  } catch {}
}

async function fetchCertimateConfig() {
  try {
    const res = await getCertimateConfig()
    certimateForm.value = { url: res.url || '', token: res.token || '' }
  } catch {}
}

function getExpiryClass(row) {
  if (!row.not_after || row.status === 'expired') return 'text-danger'
  const d = new Date(row.not_after)
  const now = new Date()
  const diff = (d - now) / (1000 * 60 * 60 * 24)
  if (diff < 30) return 'text-warning'
  return ''
}

function showDialog(row) {
  isEdit.value = !!row
  editId.value = row?.id
  if (row) {
    form.value = {
      domain: row.domain || '', issuer: row.issuer || '',
      key_algorithm: row.key_algorithm || '',
      not_before: row.not_before ? row.not_before.split('T')[0] : '',
      not_after: row.not_after ? row.not_after.split('T')[0] : '',
      subject_alt_names: row.subject_alt_names || '', source: row.source || 'certimate',
      note: row.note || ''
    }
  } else {
    form.value = { domain: '', issuer: '', key_algorithm: '', not_before: '', not_after: '', subject_alt_names: '', source: 'certimate', note: '' }
  }
  dialogVisible.value = true
}

function viewDetail(row) {
  detailCert.value = row
  detailVisible.value = true
}

async function handleSave() {
  try {
    await formRef.value.validate()
  } catch { return }
  saving.value = true
  try {
    if (isEdit.value) {
      await updateCertificate(editId.value, form.value)
      ElMessage.success('更新成功')
    } else {
      await createCertificate(form.value)
      ElMessage.success('创建成功')
    }
    dialogVisible.value = false
    fetchCerts()
    fetchStats()
  } finally {
    saving.value = false
  }
}

async function handleDelete(id) {
  await deleteCertificate(id)
  ElMessage.success('删除成功')
  fetchCerts()
  fetchStats()
}

async function handleSync() {
  syncing.value = true
  try {
    const res = await syncCertimateCertificates()
    ElMessage.success(`同步完成，共 ${res.total || 0} 张证书`)
    fetchCerts()
    fetchStats()
  } finally {
    syncing.value = false
  }
}

async function saveCertimateForm() {
  savingConfig.value = true
  try {
    await saveCertimateConfig(certimateForm.value)
    ElMessage.success('配置已保存')
    showCertimateConfig.value = false
  } finally {
    savingConfig.value = false
  }
}
</script>

<style scoped>
.certificates { max-width: 100%; }
.card-header { display: flex; align-items: center; justify-content: space-between; }
.header-left { display: flex; align-items: center; }
.header-right { display: flex; align-items: center; gap: 8px; }
.stats-row { margin-bottom: 16px; padding: 12px; background: #f5f7fa; border-radius: 8px; }
.text-danger { color: #F56C6C; font-weight: 600; }
.text-warning { color: #E6A23C; font-weight: 600; }
</style>

// web/src/pages/Certificates.jsx
import { useEffect, useState } from 'react'
import { Table, Button, Modal, Form, Input, Select, Tag, Drawer, Descriptions, Popconfirm, Empty, Statistic, Row, Col, Alert } from 'antd'
import { PlusOutlined, SettingOutlined, SyncOutlined, DeleteOutlined, EyeOutlined } from '@ant-design/icons'
import * as api from '../api/certificate'
import { useAuth } from '../context/AuthContext'
import { notify } from '../utils/toast'
import { fmtDate, fmtDateTime, calcDays } from '../utils/format'

export default function Certificates() {
  const { user } = useAuth()
  const isAdmin = user?.role === 'admin'

  const [certs, setCerts] = useState([])
  const [stats, setStats] = useState(null)
  const [loading, setLoading] = useState(false)
  const [kwInput, setKwInput] = useState('')
  const [keyword, setKeyword] = useState('')
  const [statusFilter, setStatusFilter] = useState('')

  const [dialogOpen, setDialogOpen] = useState(false)
  const [editing, setEditing] = useState(null)
  const [form] = Form.useForm()
  const [submitLoading, setSubmitLoading] = useState(false)
  const [detail, setDetail] = useState(null)

  const [configOpen, setConfigOpen] = useState(false)
  const [configForm] = Form.useForm()
  const [savingConfig, setSavingConfig] = useState(false)
  const [syncing, setSyncing] = useState(false)

  const fetchCerts = async () => {
    setLoading(true)
    try {
      const res = await api.getCertificates({ keyword, status: statusFilter })
      setCerts(res.data || [])
    } finally {
      setLoading(false)
    }
  }

  const fetchStats = () => api.getCertificateStats().then(setStats).catch(() => {})

  useEffect(() => {
    fetchCerts()
    fetchStats()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [keyword, statusFilter])

  const openDialog = (row) => {
    setEditing(row || null)
    if (row) {
      form.setFieldsValue({
        domain: row.domain,
        issuer: row.issuer || '',
        key_algorithm: row.key_algorithm || '',
        not_before: row.not_before || '',
        not_after: row.not_after || '',
        subject_alt_names: row.subject_alt_names || '',
        source: row.source || 'certimate',
        note: row.note || '',
      })
    } else {
      form.resetFields()
      form.setFieldsValue({ source: 'certimate' })
    }
    setDialogOpen(true)
  }

  const handleSave = async () => {
    const values = await form.validateFields()
    setSubmitLoading(true)
    try {
      const payload = {
        ...values,
        not_before: values.not_before ? values.not_before.split('T')[0] : '',
        not_after: values.not_after ? values.not_after.split('T')[0] : '',
      }
      if (editing) {
        await api.updateCertificate(editing.id, payload)
        notify('success', '更新成功')
      } else {
        await api.createCertificate(payload)
        notify('success', '创建成功')
      }
      setDialogOpen(false)
      fetchCerts()
      fetchStats()
    } catch {
      /* interceptor */
    } finally {
      setSubmitLoading(false)
    }
  }

  const handleDelete = async (id) => {
    await api.deleteCertificate(id)
    notify('success', '证书已删除')
    fetchCerts()
    fetchStats()
  }

  const handleSync = async () => {
    setSyncing(true)
    try {
      const res = await api.syncCertimateCertificates()
      notify('success', `同步完成，共 ${res.total || 0} 张证书`)
      fetchCerts()
      fetchStats()
    } catch {
      /* interceptor */
    } finally {
      setSyncing(false)
    }
  }

  const handleSaveConfig = async () => {
    const values = await configForm.validateFields()
    setSavingConfig(true)
    try {
      await api.saveCertimateConfig(values)
      notify('success', '配置已保存')
      setConfigOpen(false)
    } catch {
      /* interceptor */
    } finally {
      setSavingConfig(false)
    }
  }

  const openConfig = async () => {
    try {
      const res = await api.getCertimateConfig()
      configForm.setFieldsValue({ url: res.url || '', token: res.token || '' })
    } catch {
      configForm.setFieldsValue({ url: '', token: '' })
    }
    setConfigOpen(true)
  }

  const expiryClass = (row) => {
    if (!row.not_after || row.status === 'expired') return { color: '#dc2626', fontWeight: 600 }
    const days = calcDays(row.not_after)
    if (days < 30) return { color: '#d97706', fontWeight: 600 }
    return undefined
  }

  const columns = [
    { title: '域名', dataIndex: 'domain', key: 'domain', width: 210, render: (v) => <span style={{ fontWeight: 500 }}>{v}</span> },
    { title: '颁发者', dataIndex: 'issuer', key: 'issuer', width: 160, render: (v) => v || <span className="faint">-</span> },
    { title: '密钥算法', dataIndex: 'key_algorithm', key: 'key_algorithm', width: 110, render: (v) => <Tag style={{ borderRadius: 4 }}>{v || '-'}</Tag> },
    { title: '生效时间', dataIndex: 'not_before', key: 'not_before', width: 115, render: fmtDate },
    { title: '到期时间', dataIndex: 'not_after', key: 'not_after', width: 115, render: (v, r) => <span style={expiryClass(r)}>{fmtDate(v)}</span> },
    { title: '状态', dataIndex: 'status', key: 'status', width: 90, render: (v) => <Tag color={v === 'active' ? 'success' : 'error'} style={{ borderRadius: 4 }}>{v === 'active' ? '正常' : '已过期'}</Tag> },
    { title: '来源', dataIndex: 'source', key: 'source', width: 100, render: (v) => <Tag color={v === 'certimate' ? 'blue' : 'default'} style={{ borderRadius: 4 }}>{v === 'certimate' ? 'Certimate' : v || '手动'}</Tag> },
    {
      title: '操作',
      key: 'actions',
      fixed: 'right',
      width: 170,
      render: (_, r) => (
        <>
          <Button type="text" size="small" onClick={() => openDialog(r)}>编辑</Button>
          <Button type="text" size="small" icon={<EyeOutlined />} onClick={() => setDetail(r)}>详情</Button>
          <Popconfirm title="确定删除此证书？" onConfirm={() => handleDelete(r.id)}>
            <Button type="text" size="small" danger icon={<DeleteOutlined />}>删除</Button>
          </Popconfirm>
        </>
      ),
    },
  ]

  return (
    <div className="page">
      <div className="page-head">
        <div>
          <h1 className="page-title">证书管理</h1>
          <p className="page-sub">跟踪 SSL 证书生命周期，支持与 Certimate 同步</p>
        </div>
        <div className="page-actions">
          <Input.Search allowClear placeholder="搜索域名或颁发者" style={{ width: 240 }} value={kwInput} onChange={(e) => setKwInput(e.target.value)} onSearch={(v) => setKeyword(v)} />
          <Select
            allowClear placeholder="状态筛选" style={{ width: 140 }} value={statusFilter || undefined}
            onChange={(v) => setStatusFilter(v || '')}
            options={[
              { value: 'active', label: '正常' },
              { value: 'expired', label: '已过期' },
              { value: 'expiring_30', label: '30天内到期' },
            ]}
          />
          {isAdmin && (
            <>
              <Button icon={<SettingOutlined />} onClick={openConfig}>Certimate 配置</Button>
              <Button icon={<SyncOutlined />} loading={syncing} onClick={handleSync}>同步证书</Button>
            </>
          )}
          <Button type="primary" icon={<PlusOutlined />} onClick={() => openDialog(null)}>添加证书</Button>
        </div>
      </div>

      {stats && (
        <div className="panel mb-16">
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)' }}>
            <div style={{ padding: '18px 24px', borderRight: '1px solid var(--border)' }}><Statistic title="证书总数" value={stats.total} /></div>
            <div style={{ padding: '18px 24px', borderRight: '1px solid var(--border)' }}><Statistic title="正常" value={stats.active} valueStyle={{ color: '#16a34a' }} /></div>
            <div style={{ padding: '18px 24px', borderRight: '1px solid var(--border)' }}><Statistic title="已过期" value={stats.expired} valueStyle={{ color: '#dc2626' }} /></div>
            <div style={{ padding: '18px 24px' }}><Statistic title="即将到期" value={stats.expiring_soon} valueStyle={{ color: '#d97706' }} /></div>
          </div>
        </div>
      )}

      <div className="panel">
        <Table rowKey="id" columns={columns} dataSource={certs} loading={loading} size="middle" scroll={{ x: 1100 }} pagination={{ pageSize: 20, showTotal: (t) => `共 ${t} 条` }} locale={{ emptyText: <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="暂无证书" /> }} />
      </div>

      <Modal title={editing ? '编辑证书' : '添加证书'} open={dialogOpen} onOk={handleSave} onCancel={() => setDialogOpen(false)} confirmLoading={submitLoading} width={620} destroyOnClose>
        <Form form={form} layout="vertical" requiredMark={false} style={{ marginTop: 16 }}>
          <Form.Item name="domain" label="域名" rules={[{ required: true, message: '请输入域名' }]}>
            <Input placeholder="example.com" />
          </Form.Item>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
            <Form.Item name="issuer" label="颁发者"><Input placeholder="Let's Encrypt" /></Form.Item>
            <Form.Item name="key_algorithm" label="密钥算法">
              <Select options={[{ value: 'RSA 2048', label: 'RSA 2048' }, { value: 'RSA 4096', label: 'RSA 4096' }, { value: 'ECC P-256', label: 'ECC P-256' }, { value: 'ECC P-384', label: 'ECC P-384' }]} placeholder="选择算法" />
            </Form.Item>
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
            <Form.Item name="not_before" label="生效时间"><Input placeholder="YYYY-MM-DD" /></Form.Item>
            <Form.Item name="not_after" label="到期时间"><Input placeholder="YYYY-MM-DD" /></Form.Item>
          </div>
          <Form.Item name="subject_alt_names" label="Subject Alt Names"><Input.TextArea rows={2} placeholder="example.com,www.example.com" /></Form.Item>
          <Form.Item name="source" label="来源">
            <Select options={[{ value: 'certimate', label: 'Certimate' }, { value: 'manual', label: '手动' }, { value: 'other', label: '其他' }]} />
          </Form.Item>
          <Form.Item name="note" label="备注"><Input.TextArea rows={2} /></Form.Item>
        </Form>
      </Modal>

      <Drawer title={detail ? `${detail.domain} — 证书详情` : ''} open={!!detail} onClose={() => setDetail(null)} width={560}>
        {detail && (
          <Descriptions column={1} bordered size="small">
            <Descriptions.Item label="域名">{detail.domain}</Descriptions.Item>
            <Descriptions.Item label="颁发者">{detail.issuer || '-'}</Descriptions.Item>
            <Descriptions.Item label="序列号">{detail.serial_number || '-'}</Descriptions.Item>
            <Descriptions.Item label="生效时间">{fmtDateTime(detail.not_before)}</Descriptions.Item>
            <Descriptions.Item label="到期时间">{fmtDateTime(detail.not_after)}</Descriptions.Item>
            <Descriptions.Item label="Subject Alt Names">{detail.subject_alt_names || '-'}</Descriptions.Item>
            <Descriptions.Item label="密钥算法">{detail.key_algorithm || '-'}</Descriptions.Item>
            <Descriptions.Item label="签名算法">{detail.signature_algorithm || '-'}</Descriptions.Item>
            <Descriptions.Item label="状态"><Tag color={detail.status === 'active' ? 'success' : 'error'}>{detail.status === 'active' ? '正常' : '已过期'}</Tag></Descriptions.Item>
            <Descriptions.Item label="来源">{detail.source || '-'}</Descriptions.Item>
            <Descriptions.Item label="备注">{detail.note || '-'}</Descriptions.Item>
          </Descriptions>
        )}
      </Drawer>

      <Modal title="Certimate 配置" open={configOpen} onOk={handleSaveConfig} onCancel={() => setConfigOpen(false)} confirmLoading={savingConfig} width={480} destroyOnClose>
        <Alert type="info" showIcon style={{ marginBottom: 16 }} message="Certimate 使用 PocketBase 兼容 API，Token 为 superuser token。" />
        <Form form={configForm} layout="vertical" requiredMark={false}>
          <Form.Item name="url" label="API 地址" rules={[{ required: true, message: '请输入 API 地址' }]}>
            <Input placeholder="http://127.0.0.1:8090" />
          </Form.Item>
          <Form.Item name="token" label="Token" rules={[{ required: true, message: '请输入 Token' }]}>
            <Input.Password placeholder="PocketBase superuser token" />
          </Form.Item>
        </Form>
      </Modal>
    </div>
  )
}
