// web/src/views/Notifications.vue
<template>
  <div class="notifications">
    <el-card>
      <template #header>
        <div class="card-header">
          <span>通知管理</span>
          <div class="header-right">
            <el-button size="small" type="warning" @click="handleSendExpiry" :loading="sendingExpiry">
              <el-icon><Bell /></el-icon>发送到期提醒
            </el-button>
            <el-button type="primary" @click="showChannelDialog()">
              <el-icon><Plus /></el-icon>添加通知渠道
            </el-button>
          </div>
        </div>
      </template>

      <el-tabs v-model="activeTab">
        <el-tab-pane label="通知渠道" name="channels">
          <el-table :data="channels" style="width: 100%" v-loading="loading" empty-text="暂无通知渠道">
            <el-table-column prop="name" label="名称" width="180" />
            <el-table-column label="类型" width="140">
              <template #default="{ row }">
                <el-tag :type="typeColor(row.type)" size="small">{{ typeLabel(row.type) }}</el-tag>
              </template>
            </el-table-column>
            <el-table-column label="状态" width="100">
              <template #default="{ row }">
                <el-switch v-model="row.enabled" size="small" @change="handleToggle(row)" />
              </template>
            </el-table-column>
            <el-table-column label="创建时间" width="180">
              <template #default="{ row }">
                {{ new Date(row.created_at).toLocaleString('zh-CN') }}
              </template>
            </el-table-column>
            <el-table-column label="操作" width="220" fixed="right">
              <template #default="{ row }">
                <el-button text type="success" size="small" @click="showTestDialog(row)">测试</el-button>
                <el-button text type="primary" size="small" @click="showChannelDialog(row)">编辑</el-button>
                <el-popconfirm title="确定删除此通知渠道？" @confirm="handleDeleteChannel(row.id)">
                  <template #reference>
                    <el-button text type="danger" size="small">删除</el-button>
                  </template>
                </el-popconfirm>
              </template>
            </el-table-column>
          </el-table>
        </el-tab-pane>

        <el-tab-pane label="发送记录" name="logs">
          <el-table :data="logs" style="width: 100%" v-loading="logsLoading" empty-text="暂无发送记录">
            <el-table-column label="渠道" width="140">
              <template #default="{ row }">
                {{ getChannelName(row.channel_id) }}
              </template>
            </el-table-column>
            <el-table-column prop="title" label="标题" min-width="160" />
            <el-table-column prop="content" label="内容" min-width="250" show-overflow-tooltip />
            <el-table-column label="状态" width="100">
              <template #default="{ row }">
                <el-tag :type="row.status === 'success' ? 'success' : 'danger'" size="small">
                  {{ row.status === 'success' ? '成功' : '失败' }}
                </el-tag>
              </template>
            </el-table-column>
            <el-table-column prop="error" label="错误信息" width="200" show-overflow-tooltip />
            <el-table-column label="时间" width="180">
              <template #default="{ row }">
                {{ new Date(row.created_at).toLocaleString('zh-CN') }}
              </template>
            </el-table-column>
          </el-table>
        </el-tab-pane>
      </el-tabs>
    </el-card>

    <!-- Add/Edit Channel Dialog -->
    <el-dialog v-model="channelDialogVisible" :title="isEditChannel ? '编辑通知渠道' : '添加通知渠道'" width="550px" destroy-on-close>
      <el-form ref="channelFormRef" :model="channelForm" :rules="channelRules" label-width="100px">
        <el-form-item label="渠道名称" prop="name">
          <el-input v-model="channelForm.name" placeholder="例如：Bark 推送" />
        </el-form-item>
        <el-form-item label="通知类型" prop="type">
          <el-select v-model="channelForm.type" placeholder="选择类型" style="width: 100%" @change="onTypeChange">
            <el-option v-for="t in notificationTypes" :key="t.value" :label="t.label" :value="t.value" />
          </el-select>
        </el-form-item>

        <!-- Bark Config -->
        <template v-if="channelForm.type === 'bark'">
          <el-form-item label="服务器">
            <el-input v-model="barkConfig.server" placeholder="https://api.day.app" />
          </el-form-item>
          <el-form-item label="Key" prop="config">
            <el-input v-model="barkConfig.key" placeholder="your-bark-key" />
          </el-form-item>
          <el-form-item label="分组">
            <el-input v-model="barkConfig.group" placeholder="域名管理" />
          </el-form-item>
        </template>

        <!-- Telegram Config -->
        <template v-if="channelForm.type === 'telegram'">
          <el-form-item label="Bot Token" prop="config">
            <el-input v-model="telegramConfig.bot_token" placeholder="123456:ABC-DEF..." />
          </el-form-item>
          <el-form-item label="Chat ID" prop="config">
            <el-input v-model="telegramConfig.chat_id" placeholder="-1001234567890" />
          </el-form-item>
        </template>

        <!-- Email Config -->
        <template v-if="channelForm.type === 'email'">
          <el-form-item label="SMTP 服务器">
            <el-input v-model="emailConfig.smtp_host" placeholder="smtp.gmail.com" />
          </el-form-item>
          <el-form-item label="SMTP 端口">
            <el-input v-model="emailConfig.smtp_port" placeholder="587" />
          </el-form-item>
          <el-form-item label="用户名">
            <el-input v-model="emailConfig.username" placeholder="your-email@gmail.com" />
          </el-form-item>
          <el-form-item label="密码">
            <el-input v-model="emailConfig.password" type="password" show-password />
          </el-form-item>
          <el-form-item label="发件人">
            <el-input v-model="emailConfig.from" placeholder="your-email@gmail.com" />
          </el-form-item>
          <el-form-item label="收件人">
            <el-input v-model="emailConfig.to" placeholder="多个邮箱用逗号分隔" />
          </el-form-item>
          <el-form-item label="启用 TLS">
            <el-switch v-model="emailConfig.use_tls" />
          </el-form-item>
        </template>

        <!-- Webhook Config -->
        <template v-if="channelForm.type === 'webhook'">
          <el-form-item label="URL" prop="config">
            <el-input v-model="webhookConfig.url" placeholder="https://your-webhook-url.com/notify" />
          </el-form-item>
          <el-form-item label="请求方法">
            <el-select v-model="webhookConfig.method" style="width: 100%">
              <el-option label="POST" value="POST" />
              <el-option label="PUT" value="PUT" />
            </el-select>
          </el-form-item>
        </template>
      </el-form>
      <template #footer>
        <el-button @click="channelDialogVisible = false">取消</el-button>
        <el-button type="primary" @click="handleSaveChannel" :loading="savingChannel">保存</el-button>
      </template>
    </el-dialog>

    <!-- Test Dialog -->
    <el-dialog v-model="testDialogVisible" title="测试通知" width="450px">
      <el-form :model="testForm" label-width="60px">
        <el-form-item label="标题">
          <el-input v-model="testForm.title" placeholder="测试通知" />
        </el-form-item>
        <el-form-item label="内容">
          <el-input v-model="testForm.content" type="textarea" :rows="3" placeholder="这是一条测试通知" />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="testDialogVisible = false">取消</el-button>
        <el-button type="primary" @click="handleTest" :loading="testing">发送测试</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup>
import { ref, onMounted, reactive } from 'vue'
import { ElMessage } from 'element-plus'
import {
  getNotificationTypes, getNotificationChannels, createNotificationChannel,
  updateNotificationChannel, deleteNotificationChannel, toggleNotificationChannel,
  testNotificationChannel, getNotificationLogs, sendExpiryNotifications
} from '../api/notification'

const activeTab = ref('channels')
const channels = ref([])
const logs = ref([])
const loading = ref(false)
const logsLoading = ref(false)
const notificationTypes = ref([])

const channelDialogVisible = ref(false)
const isEditChannel = ref(false)
const editChannelId = ref(null)
const savingChannel = ref(false)
const channelFormRef = ref(null)

const testDialogVisible = ref(false)
const testing = ref(false)
const testChannelId = ref(null)

const sendingExpiry = ref(false)

const channelForm = ref({ name: '', type: 'bark', config: '' })
const channelRules = {
  name: [{ required: true, message: '请输入渠道名称', trigger: 'blur' }],
  type: [{ required: true, message: '请选择通知类型', trigger: 'change' }]
}

const barkConfig = reactive({ server: '', key: '', group: '域名管理' })
const telegramConfig = reactive({ bot_token: '', chat_id: '' })
const emailConfig = reactive({ smtp_host: '', smtp_port: '587', username: '', password: '', from: '', to: '', use_tls: true })
const webhookConfig = reactive({ url: '', method: 'POST' })

const testForm = ref({ title: '测试通知', content: '这是一条来自 Domain Manager 的测试通知' })

onMounted(() => {
  fetchChannels()
  fetchLogs()
  fetchTypes()
})

async function fetchTypes() {
  try {
    const res = await getNotificationTypes()
    notificationTypes.value = res.data || []
  } catch {}
}

async function fetchChannels() {
  loading.value = true
  try {
    const res = await getNotificationChannels()
    channels.value = res.data || []
  } finally {
    loading.value = false
  }
}

async function fetchLogs() {
  logsLoading.value = true
  try {
    const res = await getNotificationLogs()
    logs.value = res.data || []
  } finally {
    logsLoading.value = false
  }
}

function typeLabel(type) {
  const map = { bark: 'Bark', telegram: 'Telegram', email: '邮件', webhook: 'Webhook' }
  return map[type] || type
}

function typeColor(type) {
  const map = { bark: 'success', telegram: 'primary', email: 'warning', webhook: 'info' }
  return map[type] || 'info'
}

function getChannelName(id) {
  const ch = channels.value.find(c => c.id === id)
  return ch ? ch.name : '未知'
}

function onTypeChange() {
  channelForm.value.config = ''
}

function buildConfig() {
  const type = channelForm.value.type
  if (type === 'bark') return JSON.stringify(barkConfig)
  if (type === 'telegram') return JSON.stringify(telegramConfig)
  if (type === 'email') return JSON.stringify(emailConfig)
  if (type === 'webhook') return JSON.stringify(webhookConfig)
  return ''
}

function parseConfig(configStr, type) {
  try {
    const obj = JSON.parse(configStr || '{}')
    if (type === 'bark') { Object.assign(barkConfig, obj) }
    if (type === 'telegram') { Object.assign(telegramConfig, obj) }
    if (type === 'email') { Object.assign(emailConfig, obj) }
    if (type === 'webhook') { Object.assign(webhookConfig, obj) }
  } catch {}
}

function showChannelDialog(row) {
  isEditChannel.value = !!row
  editChannelId.value = row?.id
  if (row) {
    channelForm.value = { name: row.name, type: row.type, config: row.config || '' }
    parseConfig(row.config, row.type)
  } else {
    channelForm.value = { name: '', type: 'bark', config: '' }
    Object.assign(barkConfig, { server: '', key: '', group: '域名管理' })
    Object.assign(telegramConfig, { bot_token: '', chat_id: '' })
    Object.assign(emailConfig, { smtp_host: '', smtp_port: '587', username: '', password: '', from: '', to: '', use_tls: true })
    Object.assign(webhookConfig, { url: '', method: 'POST' })
  }
  channelDialogVisible.value = true
}

function showTestDialog(row) {
  testChannelId.value = row.id
  testForm.value = { title: '测试通知', content: '这是一条来自 Domain Manager 的测试通知' }
  testDialogVisible.value = true
}

async function handleSaveChannel() {
  try {
    await channelFormRef.value.validate()
  } catch { return }
  savingChannel.value = true
  try {
    const data = { ...channelForm.value, config: buildConfig() }
    if (isEditChannel.value) {
      await updateNotificationChannel(editChannelId.value, data)
      ElMessage.success('更新成功')
    } else {
      await createNotificationChannel(data)
      ElMessage.success('创建成功')
    }
    channelDialogVisible.value = false
    fetchChannels()
  } finally {
    savingChannel.value = false
  }
}

async function handleDeleteChannel(id) {
  await deleteNotificationChannel(id)
  ElMessage.success('删除成功')
  fetchChannels()
}

async function handleToggle(row) {
  await toggleNotificationChannel(row.id)
  ElMessage.success(row.enabled ? '已启用' : '已禁用')
}

async function handleTest() {
  testing.value = true
  try {
    await testNotificationChannel(testChannelId.value, testForm.value)
    ElMessage.success('测试发送成功')
    testDialogVisible.value = false
    fetchLogs()
  } finally {
    testing.value = false
  }
}

async function handleSendExpiry() {
  sendingExpiry.value = true
  try {
    const res = await sendExpiryNotifications()
    ElMessage.success(`到期提醒已发送，成功 ${res.sent || 0} 个渠道`)
    fetchLogs()
  } finally {
    sendingExpiry.value = false
  }
}
</script>

<style scoped>
.notifications { max-width: 100%; }
.card-header { display: flex; align-items: center; justify-content: space-between; }
.header-right { display: flex; align-items: center; gap: 8px; }
</style>

// web/src/pages/Notifications.jsx
import { useEffect, useState } from 'react'
import { Table, Tabs, Button, Modal, Form, Input, Select, Switch, Tag, Popconfirm, Empty } from 'antd'
import { PlusOutlined, BellOutlined, DeleteOutlined } from '@ant-design/icons'
import * as api from '../api/notification'
import { notify } from '../utils/toast'
import { fmtDateTime } from '../utils/format'

const TYPE_META = {
  bark: { label: 'Bark', color: 'success' },
  telegram: { label: 'Telegram', color: 'blue' },
  email: { label: '邮件', color: 'warning' },
  webhook: { label: 'Webhook', color: 'default' },
}

export default function Notifications() {
  const [channels, setChannels] = useState([])
  const [logs, setLogs] = useState([])
  const [types, setTypes] = useState([])
  const [loading, setLoading] = useState(false)
  const [logsLoading, setLogsLoading] = useState(false)
  const [activeTab, setActiveTab] = useState('channels')

  const [dialogOpen, setDialogOpen] = useState(false)
  const [editing, setEditing] = useState(null)
  const [form] = Form.useForm()
  const [submitLoading, setSubmitLoading] = useState(false)

  const [testOpen, setTestOpen] = useState(false)
  const [testChannel, setTestChannel] = useState(null)
  const [testForm] = Form.useForm()
  const [testing, setTesting] = useState(false)

  const [sendingExpiry, setSendingExpiry] = useState(false)

  // per-type config sub-forms
  const [bark, setBark] = useState({ server: '', key: '', group: '域名管理' })
  const [telegram, setTelegram] = useState({ bot_token: '', chat_id: '' })
  const [email, setEmail] = useState({ smtp_host: '', smtp_port: '587', username: '', password: '', from: '', to: '', use_tls: false })
  const [webhook, setWebhook] = useState({ url: '', method: 'POST' })

  const fetchChannels = async () => {
    setLoading(true)
    try {
      const res = await api.getNotificationChannels()
      setChannels(res.data || [])
    } finally {
      setLoading(false)
    }
  }

  const fetchLogs = async () => {
    setLogsLoading(true)
    try {
      const res = await api.getNotificationLogs()
      setLogs(res.data || [])
    } finally {
      setLogsLoading(false)
    }
  }

  useEffect(() => {
    fetchChannels()
    fetchLogs()
    api.getNotificationTypes().then((res) => setTypes(res.data || [])).catch(() => {})
  }, [])

  const buildConfig = (type) => {
    if (type === 'bark') return JSON.stringify(bark)
    if (type === 'telegram') return JSON.stringify(telegram)
    if (type === 'email') return JSON.stringify(email)
    if (type === 'webhook') return JSON.stringify(webhook)
    return ''
  }

  const parseConfig = (type, str) => {
    let obj = {}
    try {
      obj = JSON.parse(str || '{}')
    } catch {
      obj = {}
    }
    if (type === 'bark') setBark({ server: '', key: '', group: '域名管理', ...obj })
    if (type === 'telegram') setTelegram({ bot_token: '', chat_id: '', ...obj })
    if (type === 'email') setEmail({ smtp_host: '', smtp_port: '587', username: '', password: '', from: '', to: '', use_tls: false, ...obj })
    if (type === 'webhook') setWebhook({ url: '', method: 'POST', ...obj })
  }

  const openDialog = (row) => {
    setEditing(row || null)
    if (row) {
      form.setFieldsValue({ name: row.name, type: row.type })
      parseConfig(row.type, row.config)
    } else {
      form.resetFields()
      form.setFieldsValue({ type: 'bark' })
      setBark({ server: '', key: '', group: '域名管理' })
      setTelegram({ bot_token: '', chat_id: '' })
      setEmail({ smtp_host: '', smtp_port: '587', username: '', password: '', from: '', to: '', use_tls: false })
      setWebhook({ url: '', method: 'POST' })
    }
    setDialogOpen(true)
  }

  const handleSave = async () => {
    const values = await form.validateFields()
    setSubmitLoading(true)
    try {
      const payload = { ...values, config: buildConfig(values.type) }
      if (editing) {
        await api.updateNotificationChannel(editing.id, payload)
        notify('success', '更新成功')
      } else {
        await api.createNotificationChannel(payload)
        notify('success', '创建成功')
      }
      setDialogOpen(false)
      fetchChannels()
    } catch {
      /* interceptor */
    } finally {
      setSubmitLoading(false)
    }
  }

  const handleDelete = async (id) => {
    await api.deleteNotificationChannel(id)
    notify('success', '渠道已删除')
    fetchChannels()
  }

  const handleToggle = async (row) => {
    const prev = row.enabled
    setChannels((list) => list.map((x) => (x.id === row.id ? { ...x, enabled: !prev } : x)))
    try {
      await api.toggleNotificationChannel(row.id)
      notify('success', !prev ? '已启用' : '已禁用')
    } catch {
      setChannels((list) => list.map((x) => (x.id === row.id ? { ...x, enabled: prev } : x)))
    }
  }

  const openTest = (row) => {
    setTestChannel(row)
    testForm.setFieldsValue({ title: '测试通知', content: '这是一条来自 Domain Manager 的测试通知' })
    setTestOpen(true)
  }

  const handleTest = async () => {
    const values = await testForm.validateFields()
    setTesting(true)
    try {
      await api.testNotificationChannel(testChannel.id, values)
      notify('success', '测试发送成功')
      setTestOpen(false)
      fetchLogs()
    } catch {
      /* interceptor */
    } finally {
      setTesting(false)
    }
  }

  const handleSendExpiry = async () => {
    setSendingExpiry(true)
    try {
      const res = await api.sendExpiryNotifications()
      notify('success', `到期提醒已发送，成功 ${res.sent || 0} 个渠道`)
      fetchLogs()
    } catch {
      /* interceptor */
    } finally {
      setSendingExpiry(false)
    }
  }

  const getChannelName = (id) => channels.find((c) => c.id === id)?.name || '未知'

  const channelColumns = [
    { title: '名称', dataIndex: 'name', key: 'name', width: 180, render: (v) => <span style={{ fontWeight: 500 }}>{v}</span> },
    { title: '类型', dataIndex: 'type', key: 'type', width: 130, render: (v) => <Tag color={TYPE_META[v]?.color || 'default'} style={{ borderRadius: 4 }}>{TYPE_META[v]?.label || v}</Tag> },
    { title: '状态', dataIndex: 'enabled', key: 'enabled', width: 90, align: 'center', render: (v, r) => <Switch size="small" checked={!!v} onChange={() => handleToggle(r)} /> },
    { title: '创建时间', dataIndex: 'created_at', key: 'created_at', width: 170, render: fmtDateTime },
    {
      title: '操作',
      key: 'actions',
      width: 210,
      render: (_, r) => (
        <>
          <Button type="text" size="small" onClick={() => openTest(r)}>测试</Button>
          <Button type="text" size="small" onClick={() => openDialog(r)}>编辑</Button>
          <Popconfirm title="确定删除此通知渠道？" onConfirm={() => handleDelete(r.id)}>
            <Button type="text" size="small" danger icon={<DeleteOutlined />}>删除</Button>
          </Popconfirm>
        </>
      ),
    },
  ]

  const logColumns = [
    { title: '渠道', dataIndex: 'channel_id', key: 'channel_id', width: 140, render: getChannelName },
    { title: '标题', dataIndex: 'title', key: 'title', minWidth: 160, ellipsis: true },
    { title: '内容', dataIndex: 'content', key: 'content', minWidth: 240, ellipsis: true },
    { title: '状态', dataIndex: 'status', key: 'status', width: 90, render: (v) => <Tag color={v === 'success' ? 'success' : 'error'} style={{ borderRadius: 4 }}>{v === 'success' ? '成功' : '失败'}</Tag> },
    { title: '错误信息', dataIndex: 'error', key: 'error', width: 200, ellipsis: true, render: (v) => v || '-' },
    { title: '时间', dataIndex: 'created_at', key: 'created_at', width: 170, render: fmtDateTime },
  ]

  const type = Form.useWatch('type', form) || 'bark'

  return (
    <div className="page">
      <div className="page-head">
        <div>
          <h1 className="page-title">通知管理</h1>
          <p className="page-sub">配置推送渠道并查看发送记录</p>
        </div>
        <div className="page-actions">
          <Button icon={<BellOutlined />} loading={sendingExpiry} onClick={handleSendExpiry}>发送到期提醒</Button>
          <Button type="primary" icon={<PlusOutlined />} onClick={() => openDialog(null)}>添加通知渠道</Button>
        </div>
      </div>

      <div className="panel">
        <Tabs
          activeKey={activeTab}
          onChange={setActiveTab}
          items={[
            {
              key: 'channels',
              label: `通知渠道`,
              children: (
                <Table rowKey="id" columns={channelColumns} dataSource={channels} loading={loading} size="middle" pagination={false} locale={{ emptyText: <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="暂无通知渠道" /> }} />
              ),
            },
            {
              key: 'logs',
              label: `发送记录`,
              children: (
                <Table rowKey="id" columns={logColumns} dataSource={logs} loading={logsLoading} size="middle" pagination={{ pageSize: 20, showTotal: (t) => `共 ${t} 条` }} locale={{ emptyText: <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="暂无发送记录" /> }} scroll={{ x: 1000 }} />
              ),
            },
          ]}
        />
      </div>

      <Modal title={editing ? '编辑通知渠道' : '添加通知渠道'} open={dialogOpen} onOk={handleSave} onCancel={() => setDialogOpen(false)} confirmLoading={submitLoading} width={560} destroyOnClose>
        <Form form={form} layout="vertical" requiredMark={false} style={{ marginTop: 16 }}>
          <Form.Item name="name" label="渠道名称" rules={[{ required: true, message: '请输入名称' }]}>
            <Input placeholder="例如：Bark 推送" />
          </Form.Item>
          <Form.Item name="type" label="通知类型" rules={[{ required: true, message: '请选择类型' }]}>
            <Select options={types.map((t) => ({ value: t.value, label: `${t.label} — ${t.description || ''}` }))} />
          </Form.Item>

          {type === 'bark' && (
            <>
              <Form.Item label="服务器"><Input value={bark.server} onChange={(e) => setBark({ ...bark, server: e.target.value })} placeholder="https://api.day.app" /></Form.Item>
              <Form.Item label="Key" required><Input value={bark.key} onChange={(e) => setBark({ ...bark, key: e.target.value })} placeholder="your-bark-key" /></Form.Item>
              <Form.Item label="分组"><Input value={bark.group} onChange={(e) => setBark({ ...bark, group: e.target.value })} placeholder="域名管理" /></Form.Item>
            </>
          )}
          {type === 'telegram' && (
            <>
              <Form.Item label="Bot Token" required><Input value={telegram.bot_token} onChange={(e) => setTelegram({ ...telegram, bot_token: e.target.value })} placeholder="123456:ABC-DEF..." /></Form.Item>
              <Form.Item label="Chat ID" required><Input value={telegram.chat_id} onChange={(e) => setTelegram({ ...telegram, chat_id: e.target.value })} placeholder="-1001234567890" /></Form.Item>
            </>
          )}
          {type === 'email' && (
            <>
              <Form.Item label="SMTP 服务器" required><Input value={email.smtp_host} onChange={(e) => setEmail({ ...email, smtp_host: e.target.value })} placeholder="smtp.gmail.com" /></Form.Item>
              <Form.Item label="SMTP 端口" required><Input value={email.smtp_port} onChange={(e) => setEmail({ ...email, smtp_port: e.target.value })} placeholder="587" /></Form.Item>
              <Form.Item label="用户名"><Input value={email.username} onChange={(e) => setEmail({ ...email, username: e.target.value })} placeholder="your-email@gmail.com" /></Form.Item>
              <Form.Item label="密码"><Input.Password value={email.password} onChange={(e) => setEmail({ ...email, password: e.target.value })} placeholder="SMTP 授权码" /></Form.Item>
              <Form.Item label="发件人"><Input value={email.from} onChange={(e) => setEmail({ ...email, from: e.target.value })} placeholder="your-email@gmail.com" /></Form.Item>
              <Form.Item label="收件人" required><Input value={email.to} onChange={(e) => setEmail({ ...email, to: e.target.value })} placeholder="多个邮箱用逗号分隔" /></Form.Item>
              <Form.Item label="SSL(465)" valuePropName="checked">
                <Switch checked={email.use_tls} onChange={(v) => setEmail({ ...email, use_tls: v })} />
                <span className="faint" style={{ marginLeft: 8, fontSize: 12 }}>端口 465 使用隐式 TLS；其他端口自动协商 STARTTLS</span>
              </Form.Item>
            </>
          )}
          {type === 'webhook' && (
            <>
              <Form.Item label="URL" required><Input value={webhook.url} onChange={(e) => setWebhook({ ...webhook, url: e.target.value })} placeholder="https://your-webhook-url.com/notify" /></Form.Item>
              <Form.Item label="请求方法">
                <Select value={webhook.method} onChange={(v) => setWebhook({ ...webhook, method: v })} options={[{ value: 'POST', label: 'POST' }, { value: 'PUT', label: 'PUT' }]} />
              </Form.Item>
            </>
          )}
        </Form>
      </Modal>

      <Modal title="测试通知" open={testOpen} onOk={handleTest} onCancel={() => setTestOpen(false)} confirmLoading={testing} width={440} destroyOnClose>
        <Form form={testForm} layout="vertical" requiredMark={false} style={{ marginTop: 16 }}>
          <Form.Item name="title" label="标题" rules={[{ required: true, message: '请输入标题' }]}><Input /></Form.Item>
          <Form.Item name="content" label="内容" rules={[{ required: true, message: '请输入内容' }]}><Input.TextArea rows={3} /></Form.Item>
        </Form>
      </Modal>
    </div>
  )
}
